

services:
  mysql:
    image: mysql:8.0
    container_name: fidlink-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: fidlink
      MYSQL_USER: fidlink
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - fidlink-network

  redis:
    image: redis:7.2-alpine
    container_name: fidlink-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - fidlink-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fidlink-app
    restart: unless-stopped
    environment:
      DATABASE_URL: "mysql://root:password@mysql:3306/fidlink"
      PORT: 3000
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - fidlink-network
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mysql_data:
  redis_data:

networks:
  fidlink-network:
    driver: bridge
